Build/Test Tools: Fix the Travis CI build for the 3.8 branch.
Among other fixes, this backports [26871], [26909-26910], [26940], [27086], [27168], [28799], [28873], [28943], [28961], [28964], [28966-28967], [29120], [29251], [29503], [29860], [29869], [29954], [30001], [30160], [30282], [30285], [30289-30291], [30513-30514], [30516-30521], [30524], [30526], [30529-30530], [31253-31254], [31257-31259], [31622], [40241], [40255], [40257], [40259], [40269], [40271], [40446], [40449], [40457], [40604], [40538], [40833], [41082], [41303], [41306], [44993].

See #49485.

git-svn-id: https://develop.svn.wordpress.org/branches/3.8@47338 602fd350-edb4-49c9-b593-d223f7449a82

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,26 +1,91 @@
+# Travis CI Configuration File
+sudo: false
+dist: trusty
 language: php
+cache:
+  directories:
+    - $HOME/.npm
+    - vendor
+    - $HOME/.composer/cache
 
-php:
-    - "5.5"
-    - "5.2"
+# Build matrix options
+matrix:
+  include:
+    - php: 5.5
+      env: WP_TRAVISCI=travis:js
+    - php: 5.5
+      env: WP_TRAVISCI=travis:phpunit
+    - php: 5.2
+      env: WP_TRAVISCI=travis:phpunit
+      dist: precise
+  fast_finish: true
 
+# Before install, failures in this section will result in build status 'errored'
+before_install:
+  - WP_CORE_DIR=/tmp/wordpress/
+  - >
+    if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
+        mysql -e "CREATE DATABASE wordpress_tests;" -uroot
+        cp wp-tests-config-sample.php wp-tests-config.php
+        sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
+        sed -i "s/yourusernamehere/travis/" wp-tests-config.php
+        sed -i "s/yourpasswordhere//" wp-tests-config.php
+        svn checkout https://plugins.svn.wordpress.org/wordpress-importer/trunk tests/phpunit/data/plugins/wordpress-importer
+    fi
+
+# Before script, failures in this section will result in build status 'failed'
 before_script:
-    - |
-      stable='^[0-9\.]+$';
-      if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
-          phpenv config-rm xdebug.ini
-      fi
-    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
-    - cp wp-tests-config-sample.php wp-tests-config.php
-    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
-    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
-    - sed -i "s/yourpasswordhere//" wp-tests-config.php
-    - svn checkout https://plugins.svn.wordpress.org/wordpress-importer/trunk tests/phpunit/data/plugins/wordpress-importer
-    - npm install -g grunt-cli
-    - npm install
-    - php --version
-
-script: grunt test
+- |
+  # Remove Xdebug for a huge performance increase, but not from nightly:
+  stable='^[0-9\.]+$'
+  if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
+    phpenv config-rm xdebug.ini
+  fi
+- |
+  # Export Composer's global bin dir to PATH, but not on PHP 5.2:
+  if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
+    composer config --list --global
+    export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
+  fi
+- |
+  # Install the specified version of PHPUnit depending on the PHP version:
+  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
+    case "$TRAVIS_PHP_VERSION" in
+      7.1|7.0|nightly)
+        echo "Using PHPUnit 5.x"
+        composer global require "phpunit/phpunit:^5"
+        ;;
+      5.6|5.5|5.4|5.3)
+        echo "Using PHPUnit 4.x"
+        composer global require "phpunit/phpunit:^4"
+        ;;
+      5.2)
+        # Do nothing, use default PHPUnit 3.6.x
+        echo "Using default PHPUnit, hopefully 3.6"
+        ;;
+      *)
+        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
+        exit 1
+        ;;
+    esac
+  fi
+- npm --version
+- node --version
+- nvm install 0.10.48
+- npm install -g grunt-cli
+- npm install
+- npm prune
+- php --version
+- php -m
+- npm --version
+- node --version
+- which phpunit
+- phpunit --version
+- curl --version
+- grunt --version
+- git --version
+- svn --version
+script: grunt $WP_TRAVISCI
 notifications:
   slack:
     rooms:
@@ -28,4 +93,3 @@ notifications:
     on_start: never
     on_failure: always
     on_success: change
-    on_pull_requests: false
